In [12]:
import pandas as pd
import numpy as np

# Modelo Recurrentes con Embeddings a nivel de caracter

In [13]:
df = pd.read_csv('data/acetylcholinesterase_02_bioactivity_data_preprocessed.csv')

In [14]:
df.head()

molecule_chembl_id                                   canonical_smiles  \
0       CHEMBL133897              CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1   
1       CHEMBL336398         O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1   
2       CHEMBL131588  CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1   
3       CHEMBL130628      O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F   
4       CHEMBL130478          CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C   

   standard_value  standard_value_norm     pIC50  
0           750.0                750.0  6.124939  
1           100.0                100.0  7.000000  
2         50000.0              50000.0  4.301030  
3           300.0                300.0  6.522879  
4           800.0                800.0  6.096910

# Canonical_smiles To secuence

In [15]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Utilizando Tokenizer y pad_sequences de keras a nivel de caracter, obtener la entrada tokenizada. Por ejemplo:

**El smiles**:

'C[C@@]12CC[C@H]3[C@]4(C)CCC[C@@]5(C)C(=O)OCC[N+](C)(C)CCCCCCCCC[N+](C)(C)CCOC(=O)[C@]6(C)CCC[C@]7(C)[C@@H]6CC[C@@]68C[C@@H](OC(=O)CCCCCCCCC(=O)O[C@@H]1C[C@@]3(CC[C@@H]45)C2)[C@@](C)(CC[C@@H]76)C8.[Br-].[Br-]'

**Tendría que quedar algo asi (puede que no sea exacto):**

array([ 2, 11,  2, 13, 13, 12,  5,  7,  2,  2, 11,  2, 13, 16, 12, 10, 11,
        2, 13, 12, 15,  3,  2,  4,  2,  2,  2, 11,  2, 13, 13, 12, 23,  3,
        2,  4,  2,  3,  9,  6,  4,  6,  2,  2, 11,  8, 21, 12,  3,  2,  4,
        3,  2,  4,  2,  2,  2,  2,  2,  2,  2,  2,  2, 11,  8, 21, 12,  3,
        2,  4,  3,  2,  4,  2,  2,  6,  2,  3,  9,  6,  4, 11,  2, 13, 12,
       30,  3,  2,  4,  2,  2,  2, 11,  2, 13, 12, 35,  3,  2,  4, 11,  2,
       13, 13, 16, 12, 30,  2,  2, 11,  2, 13, 13, 12, 30, 36,  2, 11,  2,
       13, 13, 16, 12,  3,  6,  2,  3,  9,  6,  4,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  3,  9,  6,  4,  6, 11,  2, 13, 13, 16, 12,  5,  2, 11,
        2, 13, 13, 12, 10,  3,  2,  2, 11,  2, 13, 13, 16, 12, 15, 23,  4,
        2,  7,  4, 11,  2, 13, 13, 12,  3,  2,  4,  3,  2,  2, 11,  2, 13,
       13, 16, 12, 35, 30,  4,  2, 36, 20, 11, 25, 26, 17, 12, 20, 11, 25,
       26, 17, 12], dtype=int32)
       

**Otro ejemplo:**
smiles: 'NC(=O)O'

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 8, 2, 3, 9, 6, 4, 6], dtype=int32)

**Tener en cuenta:**

- Ver cuanta es la máxima longitud para agregar el padding correspondiente
- En el ejemplo se agrego padding a la izquierda

In [23]:
max_len_idx = df['canonical_smiles'].apply(len).argmax()
min_len_idx = df['canonical_smiles'].apply(len).argmin()

In [24]:
df['canonical_len'] = df['canonical_smiles'].apply(lambda x: len(x))

In [25]:
# Max y min 
max_sequence_len = df['canonical_len'].max()
min_sequence_len = df['canonical_len'].min()

In [26]:
max_len_idx,min_len_idx,max_sequence_len,min_sequence_len

(2929, 595, 207, 7)

In [27]:
X = df['canonical_smiles']
y = df['pIC50']

In [ ]:
# Implementar tokenización y guardar en X_seq_pad el dataset tokenizado

In [120]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [121]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [122]:
token=Tokenizer(char_level=True, lower=False)

In [123]:
token.fit_on_texts(X)

In [124]:
token.word_index

{'c': 1,
 'C': 2,
 '(': 3,
 ')': 4,
 '1': 5,
 'O': 6,
 '2': 7,
 'N': 8,
 '=': 9,
 '3': 10,
 '[': 11,
 ']': 12,
 'n': 13,
 '@': 14,
 '4': 15,
 'H': 16,
 '-': 17,
 '/': 18,
 'l': 19,
 '.': 20,
 '+': 21,
 'F': 22,
 '5': 23,
 'o': 24,
 'B': 25,
 'r': 26,
 'S': 27,
 '\\': 28,
 '#': 29,
 's': 30,
 '6': 31,
 'I': 32,
 'e': 33,
 'P': 34,
 '7': 35,
 '8': 36,
 'i': 37,
 'a': 38}

In [125]:
X_seq = token.texts_to_sequences(X)

In [126]:
X_seq_pad = pad_sequences(X_seq)

In [127]:
df['canonical_smiles'][min_len_idx]

'NC(=O)O'

In [128]:
X_seq_pad[min_len_idx]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 8, 2, 3, 9, 6, 4, 6])

# Split

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X_seq_pad, y, test_size=0.2, random_state=42)

NameError: name 'X_seq_pad' is not defined

In [131]:
len(X_train), len(y_train), len(X_test)

(4659, 4659, 1165)

In [27]:
X_train

array([[ 0,  0,  0, ...,  4,  6,  7],
       [ 0,  0,  0, ...,  4,  1,  5],
       [ 0,  0,  0, ...,  1,  5,  7],
       ...,
       [ 0,  0,  0, ...,  1,  1,  5],
       [ 0,  0,  0, ...,  4,  6,  7],
       [ 0,  0,  0, ...,  4, 24,  5]])

In [28]:
X_train[0,:]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  6,  1,  5,  1,  1,  7,  1,
        3,  1,  1,  5,  6,  4,  2,  2,  2,  3,  2,  4,  3,  2,  2,  3,  9,
        6,  4,  8,  2,  2,  2,  2,  2,  2,  2,  2,  8,  1,  5,  1, 10,  1,
        3, 13,  1, 15,  1,  1,  1,  1,  1,  5, 15,  4,  2,  2,  2,  2, 10,
        4,  6,  7])

In [29]:
X_train[-1,:]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  8,  3,  2,  4,
        2,  1,  5,  1,  1,  1,  3,  2, 27,  2,  2,  2,  2,  2,  2,  2,  2,
       27,  2,  1,  7,  1,  1,  1,  3,  2,  8,  3,  2,  4,  2,  4, 24,  7,
        4, 24,  5])

In [23]:
X_train.shape,y_train.shape

((4659, 207), (4659,))

In [132]:
X_train = np.vstack([X_train, X_train[:, ::-1]])

In [133]:
y_train = np.hstack([y_train, y_train])

In [134]:
X_train.shape,y_train.shape

((9318, 207), (9318,))

In [135]:
X_train

array([[ 0,  0,  0, ...,  4,  6,  7],
       [ 0,  0,  0, ...,  4,  1,  5],
       [ 0,  0,  0, ...,  1,  5,  7],
       ...,
       [ 5,  1,  1, ...,  0,  0,  0],
       [ 7,  6,  4, ...,  0,  0,  0],
       [ 5, 24,  4, ...,  0,  0,  0]])

In [136]:
X_train[0,:]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  6,  1,  5,  1,  1,  7,  1,
        3,  1,  1,  5,  6,  4,  2,  2,  2,  3,  2,  4,  3,  2,  2,  3,  9,
        6,  4,  8,  2,  2,  2,  2,  2,  2,  2,  2,  8,  1,  5,  1, 10,  1,
        3, 13,  1, 15,  1,  1,  1,  1,  1,  5, 15,  4,  2,  2,  2,  2, 10,
        4,  6,  7])

In [36]:
X_train[4659,:]

array([ 7,  6,  4, 10,  2,  2,  2,  2,  4, 15,  5,  1,  1,  1,  1,  1, 15,
        1, 13,  3,  1, 10,  1,  5,  1,  8,  2,  2,  2,  2,  2,  2,  2,  2,
        8,  4,  6,  9,  3,  2,  2,  3,  4,  2,  3,  2,  2,  2,  4,  6,  5,
        1,  1,  3,  1,  7,  1,  1,  5,  1,  6,  2,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0])

# Network Model

In [16]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding, Bidirectional, Dropout, Activation, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.optimizers import Adam, RMSprop
from tensorflow.keras import backend as K

In [17]:
# Métrica

def R2(y_true, y_pred):
    SS_res =  K.sum(K.square( y_true-y_pred ))
    SS_tot = K.sum(K.square( y_true - K.mean(y_true) ) )
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )

In [147]:
vocab_size = len(token.word_index)
vocab_size

38

In [148]:
max_sequence_len = X_seq_pad.shape[1]
max_sequence_len

207

# Armar modelo en keras de LSTM
El de abajo es un ejemplo propuesto pero puede armar otro similar (siempre con LSTM o GRU)

In [149]:
model = Sequential()
model.add(Embedding(vocab_size + 1, 64, input_length=max_sequence_len))
model.add(Bidirectional(LSTM(128, return_sequences=False, activation='tanh')))
model.add(Dense(100))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(50))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dense(1, activation='linear'))

In [150]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, 207, 64)           2496      
_________________________________________________________________
bidirectional_6 (Bidirection (None, 256)               197632    
_________________________________________________________________
dense_12 (Dense)             (None, 100)               25700     
_________________________________________________________________
batch_normalization_7 (Batch (None, 100)               400       
_________________________________________________________________
activation_6 (Activation)    (None, 100)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_13 (Dense)             (None, 50)               

In [151]:
model.compile(optimizer=RMSprop(learning_rate=0.005), loss='mse', metrics=[R2])

In [152]:
mcp = ModelCheckpoint('models/best_model_{epoch}', save_best_only=True, save_format="h5")
lr_reduce = ReduceLROnPlateau(monitor='loss', 
                                   factor=0.1,
                                   cooldown=0,
                                   patience=10,
                                   min_lr=1e-4)
ES=EarlyStopping(monitor='val_loss',patience=20, restore_best_weights=True)

In [153]:
history = model.fit(X_train, y_train,epochs=50, batch_size=100,  validation_data=(X_test, y_test), callbacks=[mcp, ES,lr_reduce])

Epoch 1/50
94/94 [==============================] - ETA: 0s - loss: 5.6951 - R2: -1.2499WARNING:tensorflow:From C:\Users\HP\anaconda3\envs\bioinformatic\lib\site-packages\tensorflow\python\training\tracking\tracking.py:111: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: models\best_model_1\assets
94/94 [==============================] - 165s 2s/step - loss: 5.6951 - R2: -1.2499 - val_loss: 37.5563 - val_R2: -12.4224
Epoch 2/50
94/94 [==============================] - 152s 2s/step - loss: 2.7522 - R2: -0.0703 - val_loss: 22.6043 - val_R2: -7.0534
Epoch 3/50
94/94 [==============================] - 177s 2s/step - loss: 2.7520 - R2: -0.0670 - val_loss

In [154]:
y_pred = model.predict(X_test)

# Score

In [155]:
r2 = 1 - ((y_test.values - y_pred.reshape(-1)) ** 2).sum() / ((y_test - y_test.mean()) ** 2).sum()

In [157]:
r2
# 0.4984533246797399

0.6616316411208933

In [158]:
model.save('model1.h5', )

# Load model (solo si se grabo el modelo)

In [18]:
from tensorflow.keras.models import load_model

In [19]:
model_loaded = load_model('model1.h5', custom_objects={'R2': R2})

In [20]:
y_pred = model_loaded.predict(X_test)

NameError: name 'X_test' is not defined

In [171]:
r2 = 1 - ((y_test.values - y_pred.reshape(-1)) ** 2).sum() / ((y_test - y_test.mean()) ** 2).sum()
r2

0.6616316411208933

¿Hasta que valores de r2 logró?

# Evaluación

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(color_codes=True)
sns.set_style("white")

ax = sns.regplot(x=y_test, y=y_pred, scatter_kws={'alpha':0.4})
ax.set_xlabel('Experimental pIC50', fontsize='large', fontweight='bold')
ax.set_ylabel('Predicted pIC50', fontsize='large', fontweight='bold')
ax.set_xlim(0, 12)
ax.set_ylim(0, 12)
ax.figure.set_size_inches(5, 5)
plt.show

NameError: name 'y_test' is not defined